const SLP_SPOTIFY_CLIENT_ID = process.env.SLP_SPOTIFY_CLIENT_ID
const SLP_SPOTIFY_CLIENT_SECRET = process.env.SLP_SPOTIFY_CLIENT_SECRET
const SLP_SPOTIFY_REDIRECT_URI = process.env.SLP_SPOTIFY_REDIRECT_URI
const SLP_JWT_SECRET = process.env.SLP_JWT_SECRET
const SLP_USERS_TABLE_NAME = process.env.SLP_USERS_TABLE_NAME
const SLP_SYNC_QUEUE_NAME = process.env.SLP_SYNC_QUEUE_NAME

module.exports = {
    SLP_SPOTIFY_CLIENT_ID,
    SLP_SPOTIFY_CLIENT_SECRET,
    SLP_SPOTIFY_REDIRECT_URI,
    SLP_JWT_SECRET,
    SLP_USERS_TABLE_NAME,
    SLP_SYNC_QUEUE_NAME,
}
